# Generated by Django 2.1 on 2018-09-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20180919_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
